package navalApp.navalPackage;


/**
* navalApp/navalPackage/MatrixArrayBoolHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from navalApp.idl
* lunes 4 de junio de 2018 02:47:00 PM BOT
*/

abstract public class MatrixArrayBoolHelper
{
  private static String  _id = "IDL:navalApp/naval/MatrixArrayBool:1.0";

  public static void insert (org.omg.CORBA.Any a, boolean[][] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static boolean[][] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (11, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (11, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (navalApp.navalPackage.MatrixArrayBoolHelper.id (), "MatrixArrayBool", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static boolean[][] read (org.omg.CORBA.portable.InputStream istream)
  {
    boolean value[][] = null;
    value = new boolean[11][];
    for (int _o0 = 0;_o0 < (11); ++_o0)
    {
      value[_o0] = new boolean[11];
      for (int _o1 = 0;_o1 < (11); ++_o1)
      {
        value[_o0][_o1] = istream.read_boolean ();
      }
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, boolean[][] value)
  {
    if (value.length != (11))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (11); ++_i0)
    {
      if (value[_i0].length != (11))
        throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
      for (int _i1 = 0;_i1 < (11); ++_i1)
      {
        ostream.write_boolean (value[_i0][_i1]);
      }
    }
  }

}
