package navalApp.navalPackage;


/**
* navalApp/navalPackage/MatrixArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from navalApp.idl
* lunes 4 de junio de 2018 02:47:00 PM BOT
*/

public final class MatrixArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[][] = null;

  public MatrixArrayHolder ()
  {
  }

  public MatrixArrayHolder (int[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = navalApp.navalPackage.MatrixArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    navalApp.navalPackage.MatrixArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return navalApp.navalPackage.MatrixArrayHelper.type ();
  }

}
