package navalApp;

/**
* navalApp/navalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from navalApp.idl
* lunes 4 de junio de 2018 02:47:00 PM BOT
*/

public final class navalHolder implements org.omg.CORBA.portable.Streamable
{
  public navalApp.naval value = null;

  public navalHolder ()
  {
  }

  public navalHolder (navalApp.naval initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = navalApp.navalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    navalApp.navalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return navalApp.navalHelper.type ();
  }

}
